version: "3.8"

services:
  mongo:
    container_name: learnflow_db
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo-express
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
  
  express:
    container_name: learnflow_api
    build: .
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - mongo-express
    ports: 
      - 3000:3000

networks:
  mongo-express: